'use strict';

const form = document.querySelector('.form');
const containerWorkouts = document.querySelector('.workouts');
const inputType = document.querySelector('.form__input--type');
const inputDistance = document.querySelector('.form__input--distance');
const inputDuration = document.querySelector('.form__input--duration');
const inputCadence = document.querySelector('.form__input--cadence');
const inputElevation = document.querySelector('.form__input--elevation');

//////class structure for Form -> Managing Workout data
class Workout {
  date = new Date();
  id = (Date.now() + ' ').slice(-10);

  constructor(coordinates, distance, duration) {
    this.coordinates = coordinates; // [lat,lng]
    this.distance = distance;
    this.duration = duration;
  }

  _setDescription() {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];

    this.description = `${this.type[0].toUpperCase()}${this.type.slice(1)} on ${
      months[this.date.getMonth()]
    } ${this.date.getDate()}`;
  }
}

class Running extends Workout {
  type = 'running';
  constructor(coordinates, distance, duration, cadence) {
    super(coordinates, distance, duration);
    this.cadence = cadence;

    this.calcPace();
    this._setDescription();
  }

  calcPace() {
    this.pace = this.duration / this.distance;
    return this.pace;
  }
}

class Cycling extends Workout {
  type = 'cycling';
  constructor(coordinates, distance, duration, elevationGain) {
    super(coordinates, distance, duration);
    this.elevationGain = elevationGain;

    this.calcSpeed();
    this._setDescription();
  }

  calcSpeed() {
    this.speed = this.distance / (this.duration / 60);
    return this.speed;
  }
}

//////////////////////////////////
//////////////////////////////////
//REFRACTORING for PROJECT ARCHITECTURE
//setps to learn it - in notion file

//using class structure
class App {
  #map;
  #mapEvent;
  #workouts = [];
  #mapZoomLevel = 13;

  constructor() {
    /////code in the constructor gets executed right when the application loads.

    //get user's position
    this._getPosition();

    //get data from local storage
    this._getLocalStorage();

    //attaching event handelers
    form.addEventListener('submit', this._newWorkout.bind(this));

    inputType.addEventListener('change', this._toggleElevationField);

    // for doing event delegation to move marker on the position on map by clicking the  list in the  sidebar
    containerWorkouts.addEventListener('click', this._moveToPopup.bind(this));
  }

  /////methods for functionality
  _getPosition() {
    if (navigator.geolocation)
      navigator.geolocation.getCurrentPosition(
        //first callback function for success
        this._loadMap.bind(this),
        //second callback function for error
        function () {
          alert('Could not find your location');
        }
      );
  }

  _loadMap(position) {
    console.log(position);
    ////destructured the latitude and longitude property
    const { latitude } = position.coords;
    const { longitude } = position.coords;
    //  console.log(latitude, longitude);

    //   console.log(`https://www.google.co.in/maps/@${latitude},${longitude}`);

    //with the coordinates we want to load a map and center that map at this position
    const coords = [latitude, longitude];

    ///////////////adding leaflet code
    this.#map = L.map('map').setView(coords, this.#mapZoomLevel);
    // console.log(map);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution:
        '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(this.#map);

    //////////////DISPLAYING A MAP MARKER
    //adding event handler on map object
    //map object was generated by  leaflet library
    // will use the on method on map which we will use as event listener
    //mapEvent is created by leaflet

    this.#map.on('click', this._showForm.bind(this));

    /////code from getLocalStorage method -> rendering the marker here because marker can only be loaded after map has loaded and _getLocalStorage method is called in constructor which loads as page loads and as page loads map comes -> click -> fill the form -> and then marker comes so.
    this.#workouts.forEach(work => {
      this._renderWorkoutMarker(work);
    });
  }

  _showForm(mapE) {
    this.#mapEvent = mapE;

    //removing hidden class from form elment
    form.classList.remove('hidden');

    ///to bring focus on distance input
    inputDistance.focus();
  }

  //////method for hiding form
  _hideForm() {
    //Empty the inputs
    inputDistance.value =
      inputDuration.value =
      inputCadence.value =
      inputElevation.value =
        '';

    form.style.display = 'none';
    form.classList.add('hidden');
    setTimeout(() => (form.style.display = 'grid'), 1000);
  }

  _toggleElevationField() {
    //select the closest parent with the form__input--elevation class
    inputElevation.closest('.form__row').classList.toggle('form__row--hidden');
    inputCadence.closest('.form__row').classList.toggle('form__row--hidden');
  }

  _newWorkout(e) {
    //HELPER FUNCTION to check data validation for running and cycling
    const validInputes = (...inputs) =>
      inputs.every(inp => Number.isFinite(inp));

    //HELPER FUNCTION to check for positive number
    const allPositive = (...inputs) => inputs.every(inp => inp > 0);

    e.preventDefault();

    /////creating a new workout from our user interface
    //GET DATA FROM FORM
    const type = inputType.value;
    const distance = +inputDistance.value;
    const duration = +inputDuration.value;
    let workout;

    const { lat, lng } = this.#mapEvent.latlng;

    //CREATE RUNNING OBJECT IF WORKOUT IS RUNNING
    if (type === 'running') {
      const cadence = +inputCadence.value;
      //VALIDATE DATA
      if (
        // !Number.isFinite(distance) ||
        // !NUmber.isFinite(duration) ||
        // !Number.isFinite(cadence)
        //////using the helper function data
        !validInputes(distance, duration, cadence) ||
        !allPositive(distance, duration, cadence)
      )
        return alert('Inputs have to be positive numbers.');

      ////running workout object
      workout = new Running([lat, lng], distance, duration, cadence);
    }

    //CREATE CYCLCING OBJECT IF WORKOUT IS CYCLCING
    if (type === 'cycling') {
      const elevationGain = +inputElevation.value;
      //VALIDATE DATA
      if (
        //////using the helper function data
        !validInputes(distance, duration, elevationGain) ||
        !allPositive(distance, duration)
      )
        return alert('Inputs have to be positive numbers.');

      /////cycling workout object
      workout = new Cycling([lat, lng], distance, duration, elevationGain);
    }

    //ADD NEW OBJECT TO WORKOUT ARRAY
    this.#workouts.push(workout);
    console.log(workout); //gives object
    console.log(this.#workouts); //gives array

    //DISPLAY WORKOUT MARKER ON MAP
    // const { lat, lng } = this.#mapEvent.latlng;

    //////RENDER workout on map as marker
    this._renderWorkoutMarker(workout);

    //DISPLAY/RENDER WORKOUT ON LIST
    this._renderWorkout(workout);

    //HIDE FORM + CLEAR INPUT FIELDS
    this._hideForm();

    //local Storage method
    this._setLocalStorage();

    /////click on map , form will appear,fill the form, submit the form, then marker will appear
    //this will display the marker
    //console.log(mapEvent);
    //////moved the marker showing code above
  }

  ///method for rendering workout marker on map
  _renderWorkoutMarker(workout) {
    L.marker(workout.coordinates)
      .addTo(this.#map)
      .bindPopup(
        L.popup({
          maxwidth: 250,
          minWidth: 100,
          autoClose: false,
          closeOnClick: false,
          className: `${workout.type}-popup`,
        })
      )
      .setPopupContent(
        `${workout.type === 'running' ? '🏃‍♂️' : '🚴‍♀️'} ${workout.description}`
      )
      .openPopup();
  }
  //method to create and render list in sidebar with user added workout details
  _renderWorkout(workout) {
    //for common properties in running and cycling
    let html = `
    <li class="workout workout--${workout.type}" data-id="${workout.id}">
          <h2 class="workout__title">${workout.description} </h2>
          
          <div class="workout__details">
            <span class="workout__icon">${
              workout.type === 'running' ? '🏃‍♂️' : '🚴‍♀️'
            }</span>
            <span class="workout__value">${workout.distance}</span>
            <span class="workout__unit">km</span>
          </div>

          <div class="workout__details">
            <span class="workout__icon">⏱</span>
            <span class="workout__value">${workout.duration}</span>
            <span class="workout__unit">min</span>
          </div>

`;

    //for running
    if (workout.type === 'running')
      html += `
          <div class="workout__details">
            <span class="workout__icon">⚡️</span>
            <span class="workout__value">${workout.pace.toFixed(1)}</span>
            <span class="workout__unit">min/km</span>
          </div>

          <div class="workout__details">
            <span class="workout__icon">👟</span>
            <span class="workout__value">${workout.cadence}</span>
            <span class="workout__unit">spm</span>
          </div>
        </li>
    `;

    //for cycling
    if (workout.type === 'cycling')
      html += `
         <div class="workout__details">
            <span class="workout__icon">⚡️</span>
            <span class="workout__value">${workout.speed.toFixed(1)}</span>
            <span class="workout__unit">km/h</span>
          </div>
          <div class="workout__details">
            <span class="workout__icon">⛰</span>
            <span class="workout__value">${workout.elevationGain}</span>
            <span class="workout__unit">m</span>
          </div>
        </li>
    `;
    form.insertAdjacentHTML('afterend', html);
  }

  ///method to move to the position in the map by clicking on the workout list in the sidebar
  _moveToPopup(e) {
    const workoutEl = e.target.closest('.workout');

    if (!workoutEl) return;

    const workout = this.#workouts.find(function (work) {
      return work.id === workoutEl.dataset.id;
    });
    console.log(workout);

    this.#map.setView(workout.coordinates, this.#mapZoomLevel, {
      animate: true,
      pan: {
        duration: 1,
      },
    });
  }

  //method for local Storage
  _setLocalStorage() {
    localStorage.setItem('workouts', JSON.stringify(this.#workouts));
  }

  ///method to get data out of local storage
  _getLocalStorage() {
    const data = JSON.parse(localStorage.getItem('workouts'));
    console.log(data);

    if (!data) return;

    this.#workouts = data;

    this.#workouts.forEach(work => {
      this._renderWorkout(work);
    });
  }
}
////create object from class
const appO = new App();

// let map, mapEvent;

////get the map
/////get the coordinates
/////geolocation
//////for older browser we will check if geloaction already exist
// if (navigator.geolocation)
//   navigator.geolocation.getCurrentPosition(
//     //first callback function for success
//     function (position) {
//       console.log(position);
//       ////destructured the latitude and longitude property
//       const { latitude } = position.coords;
//       const { longitude } = position.coords;
//       console.log(latitude, longitude);
//       console.log(`https://www.google.co.in/maps/@${latitude},${longitude}`);

//       //with the coordinates we want to load a map and center that map at this position
//       const coords = [latitude, longitude];

//       //////////////lecture-243
//       ///////////////adding leaflet code
//       map = L.map('map').setView(coords, 13);
//       // console.log(map);

//       L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
//         attribution:
//           '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
//       }).addTo(map);

//       //////////////shows a marker at current position
//       // L.marker(coords).addTo(map).bindPopup("A pretty CSS popup.").openPopup();

//       /////////////LECTURE- 246
//       //////////////DISPLAYING A MAP MARKER
//       //adding event handler on map object created on Line-44
//       //map object was generated by  leaflet library
//       // will use the on method on map which we will use as event listener
//       //mapEvent is created by leaflet

//       map.on('click', function (mapE) {
//         mapEvent = mapE;

//         //removing hidden class from form elment
//         form.classList.remove('hidden');

//         ///to bring focus on distance input
//         inputDistance.focus();

//         /////////this code creates a marker but now we want to
//         ///////// join marker and form submission so let's forget about this code
//         // console.log(mapEvent);
//         // const { lat, lng } = mapEvent.latlng;

//         // L.marker([lat, lng])
//         //   .addTo(map)
//         //   .bindPopup(
//         //     L.popup({
//         //       maxwidth: 250,
//         //       minWidth: 100,
//         //       autoClose: false,
//         //       closeOnClick: false,
//         //       className: 'running-popup',
//         //     })
//         //   )
//         //   .setPopupContent('workout')
//         //   .openPopup();
//       });
//     },

//     //second callback function for error
//     function () {
//       alert('Could not find your location');
//     }
//   );

//////event handler for form submission and showing marker
// form.addEventListener('submit', function (e) {
// e.preventDefault();

// //clear input fields
// inputDistance.value =
//   inputDuration.value =
//   inputCadence.value =
//   inputElevation.value =
//     '';

// /////click on map , form will appear,fill the form, submit the form, then marker will appear
// //this will display the marker
// //console.log(mapEvent);
// const { lat, lng } = mapEvent.latlng;

// L.marker([lat, lng])
//   .addTo(map)
//   .bindPopup(
//     L.popup({
//       maxwidth: 250,
//       minWidth: 100,
//       autoClose: false,
//       closeOnClick: false,
//       className: 'running-popup',
//     })
//   )
//   .setPopupContent('workout')
//   .openPopup();
// });

/////running to cycling -- chaning the input type from eleveation to cadence
// inputType.addEventListener('change', function () {
// //select the closest parent with the form__input--elevation class
// inputElevation.closest('.form__row').classList.toggle('form__row--hidden');
// inputCadence.closest('.form__row').classList.toggle('form__row--hidden');
// });
